config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }
  devise_scope :admin do
    get 'admins/sign_in', to: 'admins/sessions#new', as: :new_admin_session
    get 'admins/sign_out', to: 'admins/sessions#destroy', as: :destroy_admin_session
  end
  resources :participations do
    get '/participations/new' => 'participations#new', :as => :new_participation
  end
  resources :events
  resources :people
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'people#index'
end

app/models/participation.rb
class Participation < ApplicationRecord
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController
  before_action :set_participation, only: %i[ show edit update destroy ]

  # GET /participations or /participations.json
  def index
    @participations = Participation.all
  end

  # GET /participations/1 or /participations/1.json
  def show
  end

  # GET /participations/new
  def new
    event = Event.find(params[:event])
    puts event.event_id
    puts event.event_name
    @participation = Participation.new(event_id: event.event_id, event_name: event.event_name)
  end

  # GET /participations/1/edit
  def edit
  end

  # POST /participations or /participations.json
  def create
    @participation = Participation.new(participation_params)

    respond_to do |format|
      if @participation.save
        format.html { redirect_back(fallback_location: root_path) }
        format.json { render :show, status: :created, location: @participation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @participation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participations/1 or /participations/1.json
  def update
    respond_to do |format|
      if @participation.update(participation_params)
        format.html { redirect_to @participation, notice: "Participation was successfully updated." }
        format.json { render :show, status: :ok, location: @participation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @participation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participations/1 or /participations/1.json
  def destroy
    @participation.destroy
    respond_to do |format|
      format.html { redirect_to participations_url, notice: "Participation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participation
      @participation = Participation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def participation_params
      params.require(:participation).permit(:event_id, :uin, :event_name)
    end
end

app/helpers/participations_helper.rb
module ParticipationsHelper
end

app/views/participations/_form.html.erb
<%= form_with(model: participation) do |form| %>
  <% if participation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(participation.errors.count, "error") %> prohibited this participation from being saved:</h2>

      <ul>
        <% participation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.hidden_field :event_id %>
  </div>

  <div class="field" style="text-align:center">
    <label for="uin">Please enter your UIN:</label>
    <%= form.text_field :uin %>
  </div>

  <br>

  <div class="actions" style="text-align:center">
    <%= form.submit 'Attend this meeting' %>
  </div>
<% end %>

app/views/participations/edit.html.erb
<h1>Editing Participation</h1>

<%= render 'form', participation: @participation %>

<%= link_to 'Show', @participation %> |
<%= link_to 'Participation List', participations_path %>

app/views/participations/index.html.erb
<h1 style="text-align:center">Participations</h1>

<table>
  <thead>
    <tr>
      <th>Event ID</th>
      <th>UIN</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @participations.each do |participation| %>
      <tr>
        <td><%= participation.event_id %></td>
        <td><%= participation.uin %></td>
        <td><%= link_to 'Show', participation %></td>
        <td><%= link_to 'Edit', edit_participation_path(participation) %></td>
        <td><%= link_to 'Remove', participation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Home', people_path %>
<br>
<%= link_to 'Event List', events_path %>

app/views/participations/new.html.erb
<h1 style="text-align:center"><%= @participation.event_name %></h1>

<br><br>

<%= render 'form', participation: @participation %>

<br><br>

<div id="back">
    <%= link_to 'Back', participations_path %>
</div>

<style type="text/css">
    #back {text-align:center} 
</style>

app/views/participations/show.html.erb
<p>
  <strong>Event:</strong>
  <%= @participation.event_id %>
</p>

<p>
  <strong>UIN:</strong>
  <%= @participation.uin %>
</p>

<%= link_to 'Edit', edit_participation_path(@participation) %> |
<%= link_to 'Back', participations_path %>